### ISSUE TITLE
Cannot create labs in the local environment

### ISSUE THREAD

**Issue by 007divyachawla** [GoSecure/xxe-workshop#2]
Hello, 

As there is no Readme document in the lab or steps to create a lab we, I cannot create a lab. Please provide some documentation for the same.

**Comment by h3xstream** [comment]
I've add few instruction regarding build and how to use docker-compose.

**Comment by 007divyachawla** [comment]
Thanks, for lab 21, i have followed which is given in README but i am getting this error.

Creating network "21_rssviewer_xxe_default" with the default driver
Building web
Step 1/5 : FROM frolvlad/alpine-java:jre8-slim
jre8-slim: Pulling from frolvlad/alpine-java
6c40cc604d8e: Pull complete
1e2704e84e24: Pull complete
63d4b264644a: Pull complete
Digest: sha256:f834a7e69987ae545ec80a4609543449cef948c2378da39087e1233f6cfce1f2
Status: Downloaded newer image for frolvlad/alpine-java:jre8-slim
 ---> fc41cf2cc5a9
Step 2/5 : VOLUME /tmp
 ---> Running in fab0ed771a79
Removing intermediate container fab0ed771a79
 ---> 9d7a8c833318
Step 3/5 : COPY build/libs/rssviewer-0.0.1-SNAPSHOT.jar app.jar
ERROR: Service 'web' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat build/libs/rssviewer-0.0.1-SNAPSHOT.jar: file does not exist


For Lab 24, i am getting this error.

docker-compose up
Creating network "app_default" with the default driver
Building web
Step 1/9 : FROM frolvlad/alpine-oraclejdk8:slim
ERROR: Service 'web' failed to build : pull access denied for frolvlad/alpine-oraclejdk8, repository does not exist or may require 'docker login': denied: requested access to the resource is denied


Other 2 lab i am able to host on my localhost. Please let me know if you have any idea.

**Comment by h3xstream** [comment]
For `build/libs/rssviewer-0.0.1-SNAPSHOT.jar: file does not exist` it is because the application was not build successfully. `gradle build` is require to build the jar missing.

**Comment by h3xstream** [comment]
I think you can replace `FROM frolvlad/alpine-oraclejdk8:slim` by  `FROM frolvlad/alpine-java`.
I will have some time next week to test it.

**Comment by 007divyachawla** [comment]
Thanks @h3xstream it works thank u so much
