### ISSUE TITLE
Button "Done" links to 404 https://gosecure.github.io/

### ISSUE THREAD

**Issue by hartwork** [GoSecure/xxe-workshop#3]
Hi!

Just a quick not that when pressing button "Done" on the last page I get sent to https://gosecure.github.io/ which does not serve any content but 404. My vote for putting content up there.

Thanks and best

Sebastian

**Comment by obilodeau** [comment]
Hi Sebastian!

Thanks for letting us know of the issue. The fix is a bit convoluted but it works.

Cheers!

**Comment by hartwork** [comment]
Cool, thanks for the fix! :+1:
