### ISSUE TITLE
403 on multiples CSS files

### ISSUE THREAD

**Issue by h3xstream** [GoSecure/xxe-workshop#5]
Multiples CSS files hosted on Google CDN servers are no longer available. The issue was already reported here:
https://github.com/googlecodelabs/tools/issues/796

![image](https://user-images.githubusercontent.com/593130/199375649-b26b8877-9277-4126-a13b-bb17564dd1be.png)

There is a workaround suggest here : https://github.com/googlecodelabs/tools/issues/796#issuecomment-1298888360

**Comment by obilodeau** [comment]
I don't have time to look at this now, I'm attending an event, but I would happily merge a PR.

**Comment by obilodeau** [comment]
Fixed with #6
